require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'flags' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  def flipper_pods()
    pod 'flipper-plugin-react-native-performance', :path => "../node_modules/flipper-plugin-react-native-performance/ios", :configuration => 'Debug'
  end

  flipper_pods()

  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
